### PR TITLE
Add support for FigJam; Clean up

### LINKED ISSUE #23: Make variant switcher work for FigJam
#### Describe the desired behavior

Make it support FigJam

#### Describe the current behavior

It only supports Figma Design. The FigJam side is not tested... need to test it out. It is probably a nice and easy migration; just have to ensure all the functionality works properly

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #23

#### Changes proposed in this Pull Request:
- Added support for FigJam
- Added changelog
- ~Addressed 2 dependabot PRs~ webpack v5 frustrated me; wrote #44 and fingers crossed
- Verified that all functions work in both Figma and FigJam, light or dark theme.

#### To Test:
- Follow the [readme instructions](https://github.com/brightlayer-ui/figma-plugins/blob/dev/variant-switcher/README.md)
- To test light / dark theme: switch your system preference theme to light / dark. Figma's UI will update itself to reflect the change. The plugin should also reflect the change

### CODE REVIEW

**Comment by daileytj** [comment]
Build isn't working for me locally

Screen Shot 2022-09-30 at 11 05 51 AM

**Comment by daileytj** [comment]
Screen Shot 2022-09-30 at 11 06 26 AM
^^^ Here are your instructions ^^^ but I don't have any such option for "link existing plugin"... just this...
Screen Shot 2022-09-30 at 11 06 55 AM

There is an "import plugin from manifest" option though... ¯\_(ツ)_/¯

**Comment by huayunh** [comment]
Everything should be working now

**Review by daileytj — APPROVED** [review]
looks good to me now

**Pull request merged**
