### PR TITLE
Dark mode and Figma UI tweaks

### PR DESCRIPTION
**Pull request by jerryjappinen**
#### Changes proposed in this Pull Request:
- Dark mode support
- Updated UI text to match Figma's casing
- Minor updates to UI elements and text to match Figma's visual design

#### Issues
- Supports light/dark mode #35

#### Screenshots:
Updated version:
PR dark

PR light

Compare to native dialog:
Screenshot 2022-09-19 at 10 47 54

Old:
Current

#### To Test:
- Use Figma's theme setting to test light and dark modes.

### CODE REVIEW

**Comment by huayunh** [comment]
Jerry,

Thank you so much for your contribution! I will take a look at this PR in a few days. In the meantime, would you mind updating [this line](https://github.com/brightlayer-ui/figma-plugins/pull/40/files#diff-63b4b4e3419bbd70ef682fc69615ed4794388fee1177a5f73405ea781c6feba4R118) to use `--figma-color-text-secondary` instead? The disabled color is really hard to read at the moment. 

Huayun

**Comment by jerryjappinen** [comment]
@huayunh yeah looks like that's the appropriate value, thanks for noticing. I missed that one in the docs. Pushed an update.

**Review by huayunh — APPROVED** [review]
Code change looks good, thanks for the contribution. 

I am waiting on our IT department to address a problem that currently blocks me from running `yarn` to build the new code. I will update you in this thread once the plugin is published.

**Comment by huayunh** [comment]
Published! v6 is now available and also supports FigJam. 

Thanks again @jerryjappinen

**Pull request merged**
