### PR TITLE
Bug/27 null eerror

### LINKED ISSUE #27: TypeError: cannot read property 'Theme' of null
The plugin encounters this error, and it just won't do anything on the surface (not frozen, just stay where it is). If you peek into the console however, you will see this...

image

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #27

#### Screenshots:
Now it runs without console errors

image

#### To Test:
- See the description in [the readme](https://github.com/brightlayer-ui/figma-plugins/tree/master/variant-switcher).

### CODE REVIEW

**Comment by jeffvg** [comment]
did you find this issue locally?

**Comment by huayunh** [comment]
> did you find this issue locally?

Sorry, would you clarify "locally"? You mean if this issue exists only via the Figma desktop app? You are able to run any _published_ plugins from desktop or web browser, but you can only run the plugin under development from desktop.

> and is dev tools an option running figma locally?

The console is available for Figma's desktop app. I have never tested it in a browser. You can read about it [here](https://www.figma.com/plugin-docs/debugging/#:~:text=First%20open%20the%20Developer%20Tools,another%20tab%20is%20currently%20active.).

**Comment by jeffvg** [comment]
ok , I'm running with local copy of "master" variant switcher and I have dev tools open. I'm not able to reproduce the same error

**Review by jeffvg — APPROVED** [review]
looks good. no null errors now..

**Review by daileytj — APPROVED** [review]

**Pull request merged**
